### ISSUE TITLE
Support for Preact-X

### ISSUE THREAD

**Issue by shoojx** [developit/preact-transition-group#10]
Ask: port preact-transition-group to work with preact-x

Currently, preact-transition-group does not work with preact-x.

Thank you

**Comment by psabharwal123** [comment]
@developit ^

**Comment by aguilera51284** [comment]
+1

**Comment by psabharwal123** [comment]
fixed with https://github.com/developit/preact-transition-group/pull/11, @developit please review and publish 2.0.0

**Comment by ourfamilygithub** [comment]
@developit +1

**Comment by Julian-B90** [comment]
any new news on this?

**Comment by developit** [comment]
Apologies for taking so long - has been fixed in #11.
